### ISSUE TITLE
RTCPeerConnectionState is a better home for "closed" than RTCSignalingState is

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#530] opened 2016-03-02 15:24 UTC
enum RTCSignalingState {
    "stable",
    "have-local-offer",
    "have-remote-offer",
    "have-local-pranswer",
    "have-remote-pranswer",
    "closed" // <-- do I belong here?
};

enum RTCPeerConnectionState {
    "new",
    "connecting",
    "connected",
    "disconnected",
    "failed"
};

**Comment by alvestrand** [comment] 2016-03-08 18:14
Let's make a PR to move.

**Comment by alvestrand** [comment] 2016-03-10 15:58
Duplicate of #389

**Closed by alvestrand** 2016-03-10 15:58 UTC
Labels: Needs assignee action
