### ISSUE TITLE
Should peer identity specific steps be marked as "Feature at risk"

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-pc#2284] opened 2019-08-29 14:48 UTC
Identity was marked feature at risk in PR 1114.
There are some mandatory steps in webrtc-pc that might need to be marked as 'feature at risk'

**Comment by dontcallmedom** [comment] 2019-09-19 07:34
When we move these steps out, let's also plan on reintegrated isolated mediastream somewhere (maybe in getUserMedia)?

**Comment by alvestrand** [comment] 2019-10-17 12:38
@aboba what's the PR?

**Comment by jan-ivar** [comment] 2019-10-31 15:51
@aboba Do you have a PR here?

**Comment by aboba** [comment] 2019-10-31 20:40
@youennf - were you going to provide a PR for this one?

**Comment by youennf** [comment] 2019-11-04 07:36
I am not sure about which PR we are talking about.
Option 1:
- Remove these steps from webrtc-pc (as @dontcallmedom suggests) and add them to identity spec
Option2:
- Mark these steps as features at risk.

I think we have consensus for doing option 1. Am I correct?

**Comment by henbos** [comment] 2019-11-07 12:17
TPAC decision: "Migrate the remaining identity steps to webrtc-identity"

Didn't we decide to add some sort of placeholder "no-op steps" in webrtc-pc, and in the identity spec we extend these steps to perform identity logic?

**Comment by henbos** [comment] 2019-11-07 12:19
Changed from PR exists -> Ready for PR, correct me if that is wrong, but I don't see the a PR for this.

**Comment by henbos** [comment] 2019-11-28 19:25
Isn’t this a duplicate of #2364 at this point when we know we want to break it out? One is assigned to @youennf and one is assigned go @jan-ivar. Who takes ownership?

**Comment by jan-ivar** [comment] 2019-12-04 03:55
Closing as dup of https://github.com/w3c/webrtc-pc/issues/2364

**Closed by jan-ivar** 2019-12-04 03:55 UTC
Labels: Identity related, Ready for PR
