### ISSUE TITLE
RTCRtpReceiver.getParameters() clarification

### ISSUE THREAD

**Issue by Orphis** [w3c/webrtc-pc#2032] opened 2018-11-14 17:45 UTC
> encodings is populated based on the RIDs present in the current remote description.

What happens before negotiation? Should this be an empty array?

> The headerExtensions sequence is populated based on the header extensions that the receiver is currently prepared to receive.
The codecs sequence is populated based on the codecs that the receiver is currently prepared to receive.

What is meant by "prepared to receive"?
Does it mean that previous to negotiation those lists are similar to RTCRtpReceiver.getCapabilities()?
What happens if the user calls setCodecPreferences()?

It seems that it should be equivalent to RTCRtpSender.getParameters() and list codecs and headerExtensions that have been negotiated in the call (or an empty list before negotiation).

> rtcp.reducedSize is set to true if the receiver is currently prepared to receive reduced-size RTCP packets, and false otherwise. rtcp.cname is left out.

Why is the rtcp.cname left out? If the client knows the value, why wouldn't we then return it?

**Comment by alvestrand** [comment] 2018-11-16 08:10
This text is also missing the comment that the RIDs are based on the recv rids in the current remote description, not the send rids.
Before negotiation, the two alternatives I see are an empty array of the max size that the receiver is prepared to handle (no info, but gives a capability hint), or omitting the encodings entirely (nothing negotiated).

Yes, before negotiation, I think it makes sense to give capabilities that are the same as the receiver is capable of - this should be the same as the codec set indicated in a createOffer if no codec preferences are set.

**Comment by aboba** [comment] 2018-11-20 00:03
@orphis After negotiation, "codecs that the receiver is currently prepared to receive" refers to codecs included within m-lines that are sendrecv or recvonly.  However, with respect to what happens prior to negotiation, is the receiver "currently prepared to receive" media before SLD/SRD is called? 

I think this is a bit of a slippery slope because if we allow receiver.getParameters() to return configuration prior to negotiation, we'll need to answer some basic questions such as whether this is to reflect what would be produced from createOffer() OR what the receiver is actually configured to receive, which can be different.  Some questions: 

1. Is receiver.getParameters() affected by setCodecPreferences()? For example, if a codec is removed via setCodecPreferences(), is it returned by receiver.getParameters()?  If the goal is to reflect what codecs would appear in createOffer(), it seems odd to me to return the same codec set as would be in RTCRtpReceiver.getCapabilities() if a codec was removed via setCodecPreferences.  But if it about what "the receiver is prepared to receive" one could argue that prior to calling SLD/SRD, the receiver really isn't configured to receive anything so no codecs should be returned. 

2. Is receiver.getParameters() affected by direction? What if direction is set to "sendonly" so that the receiver is not prepared to receive any codecs?  While this does affect what is produced in createOffer(), again one could argue that it doesn't affect what "the receiver is prepared to receive" prior to completion of negotiation.

**Comment by Orphis** [comment] 2018-11-20 16:01
I would say that prior SLD/SRD, it's not prepared to receive anything and should return empty lists. After, it should then return what has been negotiated. It would be consistent with RTCRtpSender.getParameters() and much simpler to define and implement.

**Comment by alvestrand** [comment] 2018-11-29 15:40
@orphis can you write the PR?

**Comment by Orphis** [comment] 2018-11-30 14:07
I will try.

**Comment by henbos** [comment] 2019-01-22 12:45
Is this a duplicate of #1982 ?

**Comment by henbos** [comment] 2019-01-22 12:50
I removed this from the slides deck because it looks like a duplicate already covered by Jan-Ivar. Shall we close this?

**Comment by Orphis** [comment] 2019-01-22 13:08
That would work. Though we have the same problem with RTP header extensions and they should probably have a similar fix.

**Comment by aboba** [comment] 2019-02-15 20:07
Closing.  Let me know if we should reopen this.

**Closed by aboba** 2019-02-15 20:07 UTC
Labels: January 2019 interim, Ready for PR
