### ISSUE TITLE
Specify unassigned media handling

### ISSUE THREAD

**Issue by martinthomson** [w3c/webrtc-pc#39] opened 2014-12-01 16:42 UTC
In #29, @stefhak noted that we don't really specify how we handle inbound media that isn't yet assigned to a MediaStreamTrack through signaling.  This can happen with renegotiation+bundling at the offerer.  We don't specify whether to keep the data, or what to do with it.

I tend to think that this falls into the space where you have resource and quality trade-offs that aren't really very safe to specify for the general case.  A machine with lots of RAM can store several jitter buffers worth of audio and several I-frames, but there are limits to how much they can store.  There are also limits too on processing capacity to handle all that media properly.

In the same way we don't specify jitter buffer size and depth, I'm going to recommend closing this issue without at most some editorial additions.

**Comment by fluffy** [comment] 2015-04-03 17:51
The issue people seem concerned with is discarding say the first packet in an I frame. Was discussing this some folks and there were some ideas bounced around on sugesting it was a good idea (but not mandetory) to buffer something that represented a frame of video for that device

**Comment by alvestrand** [comment] 2015-04-16 12:01
Martin's PR #29 and subsequent discussion indicates that it's possible to have an indication that packets are coming in, and do something sensible that allows them to be received. Martin has promised an update that describes this  as part of a #29 update (in which case the name "mediadiscarded" is inappropriate).

**Comment by stefhak** [comment] 2015-06-02 06:57
This seem to be similar to #144  - duplicate?

**Comment by fluffy** [comment] 2015-06-02 14:22
I don't care if you close 144 as a duplicate of this but please don't close this one as it is has the conversation

**Comment by alvestrand** [comment] 2015-10-15 14:53
Peter thinks PR #293 (RTPTransceiver) addresses the early media issue.

**Comment by stefhak** [comment] 2015-10-19 11:04
Just reviewed #293, and I fail to see unassigned media being covered. Put the question to Martin and Peter.

**Comment by stefhak** [comment] 2015-10-22 13:04
Martin and Peter are happy with #293. I propose we close this Issue.

**Comment by stefhak** [comment] 2015-10-25 16:43
#293 has landed. Closing Issue.

**Closed** 2015-10-25 16:47 UTC
