### ISSUE TITLE
Receive a track multiple times

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#954] opened 2016-11-29 17:19 UTC
Hello,
while implementing we are dealing with the case of receiving the same track twice.
There are typically 2 cases:

### Receive a track previously removed
As explained in [1]:
> When the other peer stops sending a track in this manner, an ended event is fired at the MediaStreamTrack object.

The problem is that when the track is ended, it cannot be reused again [2].
So how should we manage the case of receiving again a track that has been set as ended?

### Receive the same track multiple times
The same track can be sent multiple times using addTransceiver[3].
How the receiver side should deal with this case?
A priori, we could have different MediaStreamTrack objects with the same ID and performing multiple onTrack events, but the ID should be unique, so this is not a proper solution.

## Solution proposal
As solution, I think that we must not allow sending a track more than once through addTransceiver in the same way addTrack is doing [4]:

>If an RTCRtpSender for track already exists in senders, throw an InvalidAccessError exception and abort these steps. 

And in the case that a receiver get this situation, it should reject the m-line associated.
In the case that the user wants send the same media multiple times, she should clone the track to generate a new ID.

What do you think about that?

Best!!

## Refs
[1] https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtransceiver
[2] https://www.w3.org/TR/mediacapture-streams/#idl-def-MediaStreamTrackState.ended
[3] https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtransceiver
[4] https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtrack

**Comment by mparis** [comment] 2016-12-02 09:39
Related to #583

**Comment by alvestrand** [comment] 2016-12-02 12:26
What does "the same track" mean to you?
Do you want the new incoming data stream to be connected to the same Javascript-level object?
Do you want to see a new Javascript-level object that sources the data and has the same "id" as the old one?

Speaking as an implementor:
The second one is (relatively) easy. The first one is hard.

**Comment by mparis** [comment] 2016-12-04 22:41
Hello @alvestrand,
from my perspective, two tracks are "the same track" if they have the same ID (msid in the SDP).

What I want to do is avoiding send "the same track" multiple times because the receiver side would deal with:

- Receiving again a track that has been previously set as ended.
- Having multiple tracks with the same ID.

From y point of view, these situations make not sense.

**Comment by stefhak** [comment] 2016-12-05 12:56
@mparis I agree, things could get a bit complicated. However, I have a vivid memory of us talking about this earlier and concluding "anyone using ```addTransceiver``` is an advanced user and should know what they are doing". 

Another case which is related is ```replaceTrack()```. In that case the Id of the sending track is different than the Id of the receiving track (since no SDPs are exchanged as a result of ```replaceTrack()```). And note that ```replaceTrack(withTrack)``` does not check if ```withTrack``` is already being sent.

**Comment by alvestrand** [comment] 2016-12-05 13:21
We discussed at one point whether the browser should magically detect that the sender was sending a track twice, and only transmit one copy, while reproducing two tracks on the other side. We decided against performing such magic - it is better to have a specification that behaves predictably (though not always optimally for all cases) for both implementors and app developers than to have a specification that is so complex, people don't understand what's happening.

**Comment by mparis** [comment] 2016-12-06 11:21
I agree with @alvestrand,
so, which is the predictable behavior or where is it defined?

**Comment by alvestrand** [comment] 2016-12-08 12:13
@mparis I think the rules are:
- addTrack checks if the track is already being sent, and rejects if it is
- addTransceiver and replaceTrack just cause the track to be sent. If added twice, sent twice.

**Comment by mparis** [comment] 2016-12-13 14:23
Hello @alvestrand,
what I meant if what is the predictable behavior of the receiver when it receives the same track twice.

**Comment by stefhak** [comment] 2016-12-15 15:29
Closing, the rules are clear (https://github.com/w3c/webrtc-pc/issues/954#issuecomment-265726266).

**Comment by mparis** [comment] 2016-12-16 10:38
@stefhak,
I don't have clear the rules for the receiver side and I don't find them in the specs.
The rules commented by @alvestrand were for sender side.
So, if you don't mind I think that this discussion should remain open.

**Comment by stefhak** [comment] 2016-12-16 18:53
@mparis ok, re-opening.

**Comment by mparis** [comment] 2016-12-19 20:41
@stefhak thanks!!

**Comment by stefhak** [comment] 2016-12-31 07:21
@mparis re-reading the spec it seems pretty clear to me what should happen also at the receiver side. Say that the sender side app does something like 
```
const trxA = pc.addTransceiver(trackX);
const trxB = pc.addTransceiver(trackX);
const trxC = pc.addTransceiver(trackX);
```
followed by createOffer, setLocal, send offer to remote side, which in turn does setRemote, then what happens is that three ```track``` events are fired by the remote pc, and the track in each of those events have the same id (i.e. the id of trackX). However, the remote and local app can still coordinate which is which by looking up the transceiver (which is included in the ```track``` event) and then correlate the ```mid```'s with those of ```trxA```, ```trxB``` and ```trxC```.

**Comment by stefhak** [comment] 2017-01-19 15:29
Void of any further comments I plan to create a PR that makes that the behavior outlined in https://github.com/w3c/webrtc-pc/issues/954#issuecomment-269853685 is clear in the spec.

**Comment by mparis** [comment] 2017-01-23 09:27
@stefhak, first of all sorry for the delayed response.
I think that with your comment is quite more clear and I agree with you in adding a similar explanation in the spec ;).

**Comment by aboba** [comment] 2017-02-06 20:07
@stefhak I agree with your suggested fix.

**Comment by dontcallmedom** [comment] 2017-02-08 15:48
@stefhak ping ?

**Comment by stefhak** [comment] 2017-02-09 09:06
@dontcallmedom thanks for the ping!

**Closed** 2017-02-17 18:29 UTC
Labels: External feedback, Needs assignee action, PR exists
