### ISSUE TITLE
Format of provider string for setIdentityProvider and validation

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1501] opened 2017-07-21 08:38 UTC
Currently there is no mention of what kind of format should the `provider` string be. My understanding is that it should be the `host` portion of a URL, which include domain name and port.

`setIdentityProvider()` should throw specific error if the `provider` string is not of the right format.

**Comment by martinthomson** [comment] 2017-07-25 01:00
Duplicate of #1502.

**Comment by soareschen** [comment] 2017-07-25 03:40
This is not exactly a duplicate of #1502. Here at #1501 is about the format for `provider` in `setIdentityProvider`; #1502 is about the format for `domain` in `RTCIdentityProviderDetails`.

**Closed** 2018-08-30 15:42 UTC
Labels: Identity related, Test suite issue
