### ISSUE TITLE
Editorial: Some interfaces are missing links

### ISSUE THREAD

**Issue by adam-be** [w3c/webrtc-pc#1793] opened 2018-03-08 13:40 UTC
The problem seem to affect the second half of the spec.

**Comment by Orphis** [comment] 2018-03-08 15:48
I debugged this, it's caused by this issue: https://github.com/w3c/respec/issues/1559

**Comment by Orphis** [comment] 2018-03-10 14:03
@dontcallmedom The bug in respec has been fixed, you should be able to upgrade it and fix the new warnings now :)

**Comment by Orphis** [comment] 2018-03-12 15:13
Fixed with #1797

**Closed** 2018-03-12 15:14 UTC
