### ISSUE TITLE
Codify refusing to generate an empty Offer

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-pc#1745] opened 2018-01-29 07:35 UTC
The result of creating a no-track, no-datachannel, no-offer-to-receive offer is at the moment not consistent between browsers.

Chrome will generate an offer that will not be useful for establishing an ICE transport; Firefox will refuse with the following error:

InternalError: Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel.

Chrome's behavior can lead to a confusing state where offer/answer has succeeded, but the ICETransport never reaches "connected" state. It's hard to imagine a situation where this is useful.

Suggestion: Add Firefox' behavior between section 2 and 3 in "final steps to create an offer".

**Comment by fippo** [comment] 2018-01-29 08:10
see https://github.com/rtcweb-wg/jsep/issues/832 and also https://github.com/rtcweb-wg/jsep/pull/833#issuecomment-328295695

**Comment by alvestrand** [comment] 2018-01-29 11:47
So you're saying Firefox is the one that's wrong, then?

**Comment by fippo** [comment] 2018-01-29 12:12
I just have unanswered questions that would make the Firefox version more attractive ;-)

**Comment by fippo** [comment] 2018-03-08 06:05
@jan-ivar see [here](https://github.com/rtcweb-wg/jsep/pull/833#issuecomment-328295695) -- basically this creates an edge case where you call createOffer-SLD will not result in onicecandidate firing ever

**Comment by jan-ivar** [comment] 2018-03-08 08:10
@fippo Is that a problem? Not all negotiation results in ice changes (like subsequent ones).

See @taylor-b's https://github.com/rtcweb-wg/jsep/pull/833#issuecomment-328687411

**Comment by fippo** [comment] 2018-03-08 08:13
the edge-case may be more common then. Fab, not an issue then!

**Comment by jan-ivar** [comment] 2018-03-09 15:29
We'd be ok with changing our implementation here.

**Comment by aboba** [comment] 2018-04-19 19:48
@fippo Can you submit a PR?

**Comment by alvestrand** [comment] 2019-07-08 15:36
For consistency, I'm in favor of rejecting remote offers with no m-lines.

**Comment by nils-ohlmeier** [comment] 2019-07-08 19:39
An answer with no m-lines basically means the remote side refuses to communicate. I would have expected that such and answer already results in an error of some form. If that is not the case then I agree that it should.

**Comment by rshpount** [comment] 2019-07-09 18:21
I would like to point out the offer and answer with no m= lines are technically legal. Here is one example of this:
https://tools.ietf.org/html/rfc4317#section-5.1

In general, SDP session with no m= lines or with all the m= lines refused with port 0 means that the session is active but no media is sent. This is used either to pause playback when communicating with media servers or for session warm up before the actual media is established.

**Comment by alvestrand** [comment] 2019-08-01 15:12
@nils-ohlmeier an answer with no m-lines to an offer with > 0 m-lines is syntactically illegal.
So we're only talking about the case with no m-lines in the offer.

**Comment by jan-ivar** [comment] 2019-08-01 17:26
Looks like Firefox [67](https://bugzilla.mozilla.org/show_bug.cgi?id=1531075) supports negotiating without media. I've confirmed it with [this fiddle](https://jsfiddle.net/jib1/azqw2k0f/). This means all browsers are in sync, so a change at this point seems doubtful. Closing this issue.

**Closed by jan-ivar** 2019-08-01 17:26 UTC
Labels: Needs PR
