### ISSUE TITLE
Consider merging transferable RTCDataChannel from webrtc-extensions

### ISSUE THREAD

**Issue by tguilbert-google** [w3c/webrtc-pc#2986] opened 2024-08-15 19:22 UTC
The WebRTC-extension spec has a [Transferable RTCDataChannel](https://w3c.github.io/webrtc-extensions/#rtcdatachannel-transferable) section.

WebKit has been shipping this feature for a while now. Chromium is projected to be shipping it in M130.

Should the text of the `webrtc-extensions` spec be merged back into the main spec? It might fit the [merge criteria](https://github.com/w3c/webrtc-charter/blob/gh-pages/merge-guide.md#documenting-implementations) at this point.

One point that might need additional discussion: WebKit allows transfers to DedicatedWorkers and ServiceWorkers, whereas Chromium supports transfers to DedicatedWorkers.

**Comment by alvestrand** [comment] 2024-08-19 14:37
I don't think we have any commitment to transfer to a non-dedicated worker.
It would be nice to have it work anywhere, but I suspect that we will have more difficulty for datachannels that are not within an agent cluster. @tguilbert-google can probably give a clearer answer.

**Comment by dontcallmedom** [comment] 2024-08-19 15:49
if so, this would suggest integrating the changes in webrtc-extensions limiting it to `DedicatedWorker`, and leaving the more generic `Worker` in webrtc-extensions for future consideration.

**Comment by tguilbert-google** [comment] 2024-08-19 21:17
> [...] but I suspect that we will have more difficulty for datachannels that are not within an agent cluster.

Indeed, supporting `DedicatedWorkers` was a low hanging fruit, whereas supporting `ServiceWorkers` would require some serious re-architecturing, and we can't commit to supporting it at this moment.

As a side note: a `peerconnection` is not transferrable and [closes](https://w3c.github.io/webrtc-pc/#operation:~:text=Set%20the%20%5B%5BReadyState%5D%5D%20slot%20of%20each%20of%20connection%27s%20RTCDataChannels%20to%20%22closed%22.) all of its `RTCDataChannels` when it closes. Does this limit the usefulness of transferring `RTCDataChannels` to `ServiceWorker`, since their lifetime is still tied to the `Window` that originated them?

Integrating `DedicatedWorker` only for now sounds like a good plan.

**Comment by alvestrand** [comment] 2024-08-20 06:56
The discussions we've had about PeerConnection indicate that there's some interest in making PeerConnection available in a worker, but that the cognitive and implementation problems of making it transferable were more trouble than it was worth - PeerConnection's purpose is being connected, and what happens to those connections during a transfer is going to be hard to specify.

Implementation-wise, the "real" PeerConnection lives on a separate thread in the agent cluster's memory space - so communicating between the transferred RTCDataChannels and the PeerConnection background object is relatively simple, but switching that to a cross-memory-space mechanism would be both quite complex and performance-impacting.

**Comment by youennf** [comment] 2024-08-21 06:04
I do not think the issue is service worker vs dedicated worker but out-of-agent-cluster transfer, which can happen when transferring from a window to another window/dedicated worker/service worker/shared worker.

My guess is that Chromium current implementation will be limited to transfer to same-agent cluster.
AFAIK, supporting same-agent cluster transfer is covering the most pressing needs but we identified in the past scenarios where out-of-agent-cluster transfer would be useful too.

**Comment by alvestrand** [comment] 2024-08-21 06:25
@youennf can you add some of those scenarios to webrtc-nv-use-cases?

**Closed** 2024-09-19 14:39 UTC
