### ISSUE TITLE
RTCDataChannelInit unknown member handling

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1882] opened 2018-05-31 21:11 UTC
During my data channel testing, I found a lot of weird behaviour due to options passed to `createDataChannel` that have not been interpreted by the implementation. For example:

`pc.createDataChannel('blah', { maxPacketLifeTime: 1 })` is not implemented in Chrome. It **silently** creates a reliable channel because it ignores the `maxPacketLifeTime` member.

The silent "failure" is particularly bad. Would it be possible to raise an exception in case a member of the provided `RTCDataChannelInit` options object is unknown to the implementation? This would also fix issues with typos.

Edit: A more detailed excerpt from my thesis draft:

> Many bugs have been found related to the interaction of the `createDataChannel` method with the underlying implementation. Since the `RTCDataChannelInit` object consists of members that will be ignored in case of a typing error or the member is simply not interpreted, these bugs are also silent. What makes them particularly hard to evaluate is that many attributes of `RTCDataChannel` are not implemented.
> It is already problematic that the creation of a partially reliable data channel is not trivial to verify, especially not during development since most development setups will establish peer connections on the same machine. Under no circumstances should this be paired with a fragile API mechanism prone to yield unexpected results.
> As an example, it is near impossible to create an unreliable data channel that works as expected in both Chromium and Firefox. Creating a data channel with `maxRetransmits` set to `0` results in a reliable channel in Firefox because `0` is interpreted as *undefined*. [@firefox-bug-1464917] Since setting `maxRetransmits` to anything but `0` would result in a retransmission, the only option is to set `maxPacketLifeTime` instead, for example to `0`. However, Firefox also interprets that as *undefined*. A somewhat unpleasant workaround would be to set `maxPacketLifeTime` to `1` considering that a lifetime of 1 milliseconds is very likely (if not always) to prevent retransmissions. While this workaround is applicable to Firefox, Chromium ignores `maxPacketLifeTime` and creates a reliable channel [@chromium-bug-696681]. Although using the historical member `maxRetransmitTime` works, it is uncertain whether it would work in all browsers because it has been removed from the API four years ago.
> Therefore, we think it is absolutely vital that unexpected members of the `RTCDataChannelInit` object are being handled by throwing an exception.

**Comment by alvestrand** [comment] 2018-06-01 01:58
This "feature" is unfortunately the result of the WebIDL definition of "dictionary", where members that are not known to the implementation are ignored by definition - it is *specified* to act as if they don't exist.

Closing as "working as intended", even though I agree with you that this will surprise users.
(Note: The reason why MediaTrackSupportedConstraints exists is exactly the same problem.)

**Closed by alvestrand** 2018-06-01 01:58 UTC

**Comment by lgrahl** [comment] 2018-06-01 02:05
I feared this might be the case. As a proposal for future APIs, we could apply the builder pattern which is more explicit and would allow for exceptions as well as testing whether the feature exists:

```js
const dc = pc.createDataChannel('<label>')
  .withProtocol('<protocol>')
  .withMaxRetransmits(0)
  .build()
```

(I'm not proposing this for `createDataChannel` atm since it would of course break the API.)
