### ISSUE TITLE
currentLocalDescription: incongruous explanation

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#584] opened 2016-04-15 09:43 UTC
Hello,
if I am not wrong, the currentLocalDescription is the one that _was successfully negotiated_ and NOT the last updated by setLocalDescription because you cannot have it without having negotiated with the other peer, isn't it?

See this paragraph:
The currentLocalDescription attribute represents the local RTCSessionDescription that was successfully negotiated the last time theRTCPeerConnection transitioned into the stable state plus any local candidates that have been generated by the ICE Agent since the offer or answer was created. This attribute is updated by setLocalDescription(). [1]

Refs
[1] http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-currentLocalDescription

**Comment by mparis** [comment] 2016-04-15 09:49
The same for currentRemoteDescription

**Comment by taylor-b** [comment] 2016-04-18 18:11
So specifically, the problem is the sentence "This attribute is updated by setLocalDescription()."? Since it can be updated by setLocalDescription *or* setRemoteDescription? I agree, this should be corrected.

**Comment by jan-ivar** [comment] 2016-04-18 18:22
@taylor-b It is my understanding it is updated by the transition to `stable` state.

**Comment by alvestrand** [comment] 2016-04-21 15:02
Fixed by #580, I think.

**Closed by alvestrand** 2016-04-21 15:02 UTC

**Comment by jan-ivar** [comment] 2016-04-22 23:06
@alvestrand I don't think so. https://github.com/w3c/webrtc-pc/pull/580 still says that `currentLocalDescription` and `currentRemoteDescription` are updated by `setLocalDescription` and `setRemoteDescription` respectively, when I believe - and @mparis let me know if you disagree - it is more correct to say they are updated by the transition to `'stable'` state.

**Comment by mparis** [comment] 2016-04-25 12:50
@jan-ivar @alvestrand, what do you think about removing "This attribute is updated by setLocalDescription()" like in #/594?
