### ISSUE TITLE
setRemoteDescription error when rtcpMuxPolicy is "require" and SDP is missing "a=rtcp-mux"

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1235] opened 2017-05-24 05:56 UTC
in the constructor NotSupportedError is thrown on an attempt to use a negotiate in a browser which does not support it. If such a browser attempts to set a remote RTCSessionDescription should it reject with a specific error? The current error behaviour would be a RTCError from step 3 of that algorithm.

Also, the setConfiguration algorithm also has this:
> If configuration.rtcpMuxPolicy is set and its value differs from the connection's rtcpMux policy, throw an InvalidModificationError.

If the browser does not implement 'negotiate' and an attempt is made to use setConfiguration to change this wouldn't it be more consistent to return NotSupportedError too?

This would also allow streamlining the constructor steps by merging step 3 (mux policy) into step 5 (set the configuration). From an implementation perspective i'd prefer to throw the error from a single place.
Even if we want different errors that would be possible by tweaking the language above.

@taylor-b you might have an opinion already

**Comment by taylor-b** [comment] 2017-05-24 17:55
I don't think the browser not implementing "negotiate" is relevant to this issue. The issue is really "what error do you get when the RTCP mux policy is 'require'?". I don't see what "step 3" you're referring to; I see these steps though (2.1.4 and 2.1.5):

> If the content of description is not valid SDP syntax, then reject p with an RTCError...

> If the content of description is invalid, then reject p with a newly created InvalidAccessError...

This error fits more as "invalid content" than "not valid SDP syntax", so I guess it would be an `InvalidAccessError` as specified today. It may make sense to change this to also be an `RTCError` with an SDP line number; @aboba, what do you think?

As for `setConfiguration`: I don't think it makes a big difference if you get an `InvalidModificationError` or a `NotSupportedError`. If you'd prefer it being changed, I'm fine with that.

**Comment by fippo** [comment] 2017-05-24 18:05
oops, I got the step number wrong. :-/ I meant step 4 in "set an RTCSessionDescription".

Shall I make a PR to change the error and another one to remove it from the 4.3.1 constructor (step 3) to the "set a configuration" algorithm? I don't think "initialize the ice agent" depends on checking the rtcpMuxPolicy before that... if it does then probably other things currently in "set a configuration" like the ice servers do as well.

**Comment by taylor-b** [comment] 2017-05-25 20:59
@fippo Sounds good to me.

**Comment by stefhak** [comment] 2018-07-18 08:34
@fippo could you make that PR (https://github.com/w3c/webrtc-pc/issues/1235#issuecomment-303805077)?

**Comment by fippo** [comment] 2018-07-22 13:00
@stefhak I thought I did in #1907 -- but only the second PR for moving stuff to setConfiguration. Throwing an error in SRD is in #1942

**Comment by stefhak** [comment] 2018-07-23 14:34
@fippo great, thanks. I guess we can close this Issue once #1942 has landed!?

**Comment by fippo** [comment] 2018-07-23 14:35
that will happen automagically due to "fixes" :-)

**Closed** 2018-08-02 14:05 UTC
