### ISSUE TITLE
Inconsistent behaviors of addTrack compared to addTranseiver and sender.replaceTrack

### ISSUE THREAD

**Issue by soareschen** [w3c/webrtc-pc#1386] opened 2017-06-15 03:50 UTC
- `addTrack` verifies that given track is not not found in any existing sender, and otherwise throws `InvalidAccessError`. However the same checking is not done in `addTransceiver(track)` and `sender.replaceTrack`.

- `addTrack` tries to reuse existing sender that is compatible and with null track, `addTransceiver(track)` creates new transceiver regardless.

- `addTrack` mentions about checking the origin of track, `addTransceiver(track)` doesn't.

- Some (informational?) descriptions in `addTransceiver`, e.g. effects on creating offer and session descriptions, are not found in `addTrack`.

I see quite some overlaps between `addTrack` and `addTransceiver`. Is it correct that `addTrack` is there for legacy reasons? Does it make sense to factor out the common steps and put them in a common section?

**Comment by aboba** [comment] 2017-06-15 05:43
The note in Section 5 explains that the same track can be sent multiple times via in `addTransceiver(track)` and `sender.replaceTrack` which is why the check is not done. `addTransceiver(track)` always creates a new transceiver by design.

The text on origin checks might best be placed somewhere else so as to apply more generally.

**Comment by soareschen** [comment] 2017-06-15 06:52
> The note in Section 5 explains that

I see. Missed that one. Thanks for pointing!

**Comment by aboba** [comment] 2017-06-18 02:26
Since this question has morphed into Issue https://github.com/w3c/webrtc-pc/issues/1407 I am closing it.

**Closed by aboba** 2017-06-18 02:26 UTC
Labels: question
