### ISSUE TITLE
RTCPeerConnection incorrectly adds operation overload via a partial interface

### ISSUE THREAD

**Issue by saschanaz** [w3c/webrtc-pc#1897] opened 2018-06-19 01:44 UTC
http://w3c.github.io/webrtc-pc/#method-extensions

[The Web IDL spec](https://heycam.github.io/webidl/#idl-overloading) says overloads must not be added via any partial types:

>Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.

Instead they must be in the same interface definition.

I suggest we merge [4.4.2](http://w3c.github.io/webrtc-pc/#interface-definition) and [4.4.3.1](http://w3c.github.io/webrtc-pc/#method-extensions).

**Comment by alvestrand** [comment] 2018-06-28 14:54
Merging the sections would be highly confusing.

**Comment by henbos** [comment] 2018-06-28 14:56
Possible workaround

Real section
interface RTCPeerConnection extends RTCPeerConnectionLegacyExtension { ... }
Legacy section
interface RTCPeerConnectionLegacyExtension { ... };

**Comment by saschanaz** [comment] 2018-06-28 22:58
>Merging the sections would be highly confusing.

I think we can merge only IDLs, and keep the docs separate.

>Possible workaround

AFAIK adding a different signature in a sub-interface will override the original one.

**Comment by bzbarsky** [comment] 2018-06-29 14:56
> Merging the sections would be highly confusing.

Merging the IDLs would be less confusing, because it would not have the "oh, actually the behavior is totally not what you thought" effect that you get now.  That's why the restriction is in the IDL spec.

The prose can and should stay separated.

**Comment by jan-ivar** [comment] 2018-07-02 21:18
@bzbarsky What wrong behavior would it lead to? I added a simple note, but that might not suffice if there's a significant behavior difference here.

**Comment by bzbarsky** [comment] 2018-07-02 21:55
> What wrong behavior would it lead to?

In the specific case of RTCPeerConnection, say you have code that does:

    createOffer(someOptions, 5)

If you are only aware of the one-arg version of the function, you expect this to do the behavior corresponding to `someOptions`.  With the three-arg overload in play, this will always return a rejected promise, because `5` cannot be coerced to `RTCPeerConnectionErrorCallback`.

**Comment by jan-ivar** [comment] 2018-07-19 12:39
With the partial interface in the same spec document, I think it would be hard for an implementer to be unaware, especially with the note now added in https://github.com/w3c/webrtc-pc/pull/1922. Closing.

**Closed by jan-ivar** 2018-07-19 12:39 UTC
Labels: PR exists

**Comment by saschanaz** [comment] 2018-07-19 13:11
Still an incorrect IDL, though. 🤔

**Comment by bzbarsky** [comment] 2018-07-19 15:12
> I think it would be hard for an implementer to be unaware

The issue is whether an _author_ is aware...  I understand the desire to have the optional legacy section, and I wish there were a good way to do that sort of thing in  general without the  corresponding confusion about what the behavior is when the optional legacy bits _are_ implemented...

(Of course in practice they are implemented by all browsers in this case, right?)

**Comment by jan-ivar** [comment] 2018-07-20 17:39
> (Of course in practice they are implemented by all browsers in this case, right?)

Safari Tech Preview (I run an ancient version because OS) has a "Develop / WebRTC / Enable Legacy WebRTC API" pulldown menu option that is off by default, but when I [test it](https://jsfiddle.net/jib1/qx4z72at/), callbacks work regardless, so who knows. Again, this is outdated info, and I don't know what they've decided in their latest version.

In any case, browsers may drop legacy features in the future based on usage telemetry.
