### ISSUE TITLE
order of transceivers, senders/receivers?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#1669] opened 2017-11-21 18:38 UTC
split from [this comment](https://github.com/w3c/webrtc-pc/issues/1586#issuecomment-3460708949)

http://w3c.github.io/webrtc-pc/#dfn-collecttransceivers says:
```
The conversion from the transceiver set to the sequence is user agent defined and the 
order does not have to be stable between calls.
```
(there is similar text in mediacapture-main [wrt to the track set](https://w3c.github.io/mediacapture-main/#track-set)

However [JSEP](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-5.2) implies that the offer is created 
```
in the order the RtpTransceivers were added to the PeerConnection.
```

Given that I would assume that the result of getTransceivers, getSender or getReceivers is in the order they were added to the peerconnection which is stable and defined by JSEP, not by the user agent.

Is there any particular reason not to assume order?

**Comment by alvestrand** [comment] 2017-11-22 05:56
The reason for the non-ordering of tracks in streams was a long discussion about how it should work - if I remember rightly, the issue is that if the ordering matters, you have to keep it consistent and stable in the face of reordering.
(For tracks in streams, this matters because tracks on a video element (at least at that time) had ordering, so the mapping would have an observable effect.)
This means that you have to define not only whehter stream.add(a); stream.add(b); stream.add(c) produces (a, b, c) or not, but you have to define whether streaam.add(a); stream.add(b); stream.add(c); stream.remove(b) produces (a, <blank>, c) or (a, c) - and if you re-add b, do you get (a, b, c) or (a, c, b)?
Other ideas included sorting on "id" (consistent, but unpredictable).
In the end we decided to abandon the idea of ordering and leave it implementation-defined.

I don't remember a specific decision to not impose order on other sets, but similar arguments may have applied - or the language may have gotten inherited.

The JSEP text seems to require that a specific piece of data is kept with transceivers - addition order. Transceivers in the SDP (the place where ordering matters) can't be removed, or reordered once they're added to the SDP, so the reordering arguments in MedaCapture don't seem to apply as much.
But given the *way* transceivers are added to the SDP, their order won't necessarily be addition order (they're the same for initial offers, but in answers and subsequent offers, they are assigned to "appropriate" m-sections, not assigned in 1-2-3 order), so the create-time ordering and the media-section ordering won't be consistent with each other.

Any ordering requirement constrains implementation. So I would only want to impose ordering if it is a) well-defined for all cases and b) useful.

Does create-time ordering satisfy those criteria?

**Comment by fippo** [comment] 2017-11-22 07:48
> but in answers and subsequent offers, they are assigned to "appropriate"

in SRD already, [see here](https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-20#section-5.6)
(`according to the canonical order described in Section 5.2.1` which essentially media-section order from the remote side mixed with the local side processed in create-time order)

If an implementation were to choose media-section order, adding a video track, then an audio track and setting a remote description which is a-v changes the order.

Lexical ordering by mid... will probably be the same as ordering a MST track set by id, consistent but unpredictable.

> Any ordering requirement constrains implementation.

I'd say they are already constrained by JSEP requirements but can see an argument that JSEP does not define getTransceivers() and therefore does not expose its ordering.

> So I would only want to impose ordering if it is a) well-defined for all cases and b) useful.

(c) consistent. addition order does not change even though developers should be *strongly* encouraged to always use .forEach(), .find() and .map() on the result of getTransceivers() et al instead of making assumptions.

**Comment by alvestrand** [comment] 2017-11-23 15:51
what's the use case for this ordering?

**Comment by jan-ivar** [comment] 2017-11-28 17:58
@alvestrand A use-case would be:
```js
pc.addTransceiver("audio");
pc.addTransceiver("video");
pc.getTransceivers()[0].direction = "recvonly";
pc.getTransceivers()[1].direction = "inactive";
```
Of course there are other ways to write it, but this is a convenient way to keep track of transceivers.

In fact, Firefox's [own tests](https://reviewboard.mozilla.org/r/171860/diff/13#index_header) rely on this pattern, even though it is not standard.

Another way to look at: if this ends up working in all browsers, we should probably standardize it.

**Comment by jan-ivar** [comment] 2017-11-28 18:45
>  adding a video track, then an audio track and setting a remote description which is a-v changes the order.

You're the answerer here I think, so should the order of your transceivers be the order of the m-lines or the order you created them in?

> media-section ordering won't be consistent with each other.

Indexes can't match once you stop a transceiver that is not the last one.

I think we want creation order.

**Comment by fippo** [comment] 2017-11-28 18:51
> Indexes can't match once you stop a transceiver that is not the last one.

I missed that. So yeah, remote-order doesn't gain much.

👍 on creation order.

**Closed** 2018-01-18 15:40 UTC
