### ISSUE TITLE
What happens if ufrag differs between different SDPs applied

### ISSUE THREAD

**Issue by stefhak** [w3c/webrtc-pc#1311] opened 2017-06-01 11:03 UTC
From https://lists.w3.org/Archives/Public/public-webrtc/2016Sep/0071.html:

"Let say offer/answer done with ufrag1 and PC is in stable state. Now a reoffer is done a new ufrag2. ICE start gathering candidates and PC is not in stable state. The currentLocalDescription returns SDP with ufrag1 while pendingLocalDescription returns SDP with ufrag2. Any new ICE candidates that are being gathered should be added to pendingLocalDescription but stuff with ufrag2 should not be added to SDP with ufrag1 in the currentLocalDescription. Think the spec has this wrong. An interesting case to consider is in the case where ufrag2 did not change and was ufrag1, then seems like it should be added to bother."

Assigning to @taylor-b since this seems related to the unverified media discussion.

**Comment by stefhak** [comment] 2017-06-06 07:20
Reassigning to @pthatcherg since @taylor-b seems over-assigned! Can you comment @pthatcherg ?

**Comment by taylor-b** [comment] 2017-06-06 18:30
Sorry, this was on my todo list but it's getting somewhat backed up. Anyway, this looks like it's a duplicate of #1227.

**Closed by taylor-b** 2017-06-06 18:30 UTC
