### ISSUE TITLE
getting the fingerprint of a RTCCertificate?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-pc#720] opened 2016-06-27 06:41 UTC
[RTCCertificate](https://w3c.github.io/webrtc-pc/#rtccertificate-interface) doesn't have a way to get the fingerprint of the generated certificate which would be useful for managing certificates (basically: "what fingerprint did I use when last talking to peer X").

What about adding a getFingerprint() method akin to getFingerprint()?

The [ORTC definition](http://ortc.org/wp-content/uploads/2016/05/ortc.html#rtccertificate-interface) has a fingerprint attribute which allows accessing both the fingerprint value and the algorithm. That seems like a slightly better way to do it but would require pulling in the whole RTCDtlsFingerprint definition.

**Comment by fluffy** [comment] 2016-09-21 12:46
Is this a duplicate of #738

**Comment by aboba** [comment] 2016-10-05 21:34
Can we close this Issue?

**Comment by alvestrand** [comment] 2016-10-06 14:54
Fixed by #738

**Closed by alvestrand** 2016-10-06 14:54 UTC
Labels: July interim topic, PR exists, TPAC 2016
