### ISSUE TITLE
Missing sender identifier attribute (msid)

### ISSUE THREAD

**Issue by jcaden** [w3c/webrtc-pc#705] opened 2016-06-15 08:15 UTC
`replaceTrack` documentation says: 

> To avoid track identifiers changing on the remote receiving end when a track is replaced, the sender must retain the original track identifier and stream associations and use these in subsequent negotiations.

At this point, I can't see a way to get the identifier that a sender is using. If you don't execute `replaceTrack`, you can use track's identifier, but if you change the track there is no way to get it.

It will be great to add a public attribute in the API providing access to the identifier that is being used by the sender.

**Comment by stefhak** [comment] 2016-06-16 12:00
The way to get that info over to the receiver would be an SDP O/A procedure, and that is what we wanted to avoid with replaceTrack. If the id is important, send it over with some app proprietary signaling, or use removeTrack+addTrack to get the new track, and its Id, to the remote end-point.

**Comment by jcaden** [comment] 2016-06-16 12:49
But, as long as we are defining a API to avoid making modifications in SDP, shouldn't it be important to let programmers access this information using this API?

Maybe my question was not clear enough. What I meant is that there is no way for the sender peer to know what msid is being used for sending once the `replaceTrack` method is called. Of course, the receiver peer is not affected at all by this changes, as the msid won't change for them.

Without the `msid` property in the sender there is no other way to get this information but parsing the SDP, what in my opinion should not be necessary, that's why this API makes sense, to not require SDP parsing or modifications.

**Comment by stefhak** [comment] 2016-06-21 06:36
Ah, then I get it. I still think that what matters is the id of the MediaStreamTrack, because that is what would be referred to. I mean that the app of the sending peer can tell the app of the receiving peer that "id xx represents front facing camera and id yy represents room facing camera" as an example. This means that if app of sender peer does not know xx and yy this would not work.
I have not looked into this in detail, but are there situations this could happen?

**Comment by stefhak** [comment] 2016-08-05 07:29
Closing as we've not heard back from @jcaden. Feel free to re-open if you think that is needed.

**Comment by jcaden** [comment] 2016-08-05 07:58
Sorry I didn't replied because I need to find better examples and use cases. I'll reopen the issue when I have a clear example.

**Comment by stefhak** [comment] 2016-08-05 09:35
Sounds good. BTW, note that replaceTrack() is specified to fail if a re-negotiation would be needed. The idea is that nothing in the SDP negotiated session would change, just the source of the media sent. This means that msid would remain unchanged (not sure if it makes a difference in your example, just wanted to highlight).

**Comment by jcaden** [comment] 2016-08-05 09:55
That's exactly the point of my question. As the sender has a fixed msid once you perform a replaceTrack it is impossible to know (using the API) what's the msid that is being used by the sender.

**Comment by stefhak** [comment] 2016-08-05 10:20
If you know it before you do replaceTrack() you would know it afterwards as well as it is unchanged. This issue seems unrelated to replaceTrack().

**Comment by jcaden** [comment] 2016-08-05 10:33
I just miss this property in the sender because without it you force the application to store the first msid if it needs it later. If you think that this property in the sender is not necessary you can close the issue and wait for a real use case.

**Comment by stefhak** [comment] 2016-08-05 11:11
The issue is already closed :-) However I don't want to close the discussion until we've settled. The case would be would be:
- The sending application sends MediaStreamTrack (MST) with id=A over the peerconnection
- The remote application gets a MST with id=A from the peerconnection
- The sending application does replaceTrack with another MST (id=B)
- At the remote end nothing happens - the MST there still has id=A
- The sending app looses reference to MST A and wants to find out which Id it had
To me personally it seems like the sending application could store the Id (A) of the original MST if it is important to keep track of it.

**Comment by jcaden** [comment] 2016-08-05 11:49
It's just an opinion, I prefer that the library stores the original id (it maybe have it already stored for internal purposes) and then expose this information to the user.

There is also a track attribute on the sender and you could also store the last track assigned to each sender but its easier if the library does it for you.

**Comment by stefhak** [comment] 2016-08-18 08:44
@jcaden I can see where you are coming from, and perhaps there is a point. Would you be willing to propose a solution (API), either to the list or in the form of a PR? That would probably make it easier to get feedback from others.

**Comment by stefhak** [comment] 2016-10-20 12:02
I think we can close this PR now, if @jcaden is unhappy he can re-open.

**Closed** 2016-12-15 15:52 UTC
Labels: External feedback, Needs submitter action
