### ISSUE TITLE
RTCDataChannel.id assignment

### ISSUE THREAD

**Issue by lgrahl** [w3c/webrtc-pc#1818] opened 2018-03-27 22:49 UTC
I'm currently writing a bunch of WPT tests and found that channel ID assignment in particular trips all implementations in several places. I found out that channel id assignment is extremely hard to get right since it can fail in at least three different places even though the spec only speaks of one (the second case):

1. Before the DTLS role is known when creating a data channel (this is not defined in the spec since no ID is being assigned at that point but people aren't silly and do test for the maximum number of streams they support).
2. As soon as the DTLS role is known and already created data channels will be assigned an ID or closed followed by an error event (in case no ID can be assigned).
3. As soon as the SCTP association is established and the number of streams has been negotiated. The negotiated number may be lower than what has been assumed earlier.

I'm not sure if we need to update the spec but we probably should because at least the third case is not covered.
The second case is covered by the spec but DTLS role changes in a subsequent remote description after the channels have been assigned an ID is not covered... I don't even know what to suggest for that... just panic? :wink: 

(The Cpt. Hindsight in me says: A promise for `createDataChannel` would have been much less prone to error because we could have delayed all of this until the SCTP association had been established.)

Edit: My suggestion would be to specify that IDs are to be assigned after the SCTP association has been established and before the channel is opened. Before that, the ID should be `null` unless it's a negotiated channel.

**Comment by nils-ohlmeier** [comment] 2018-03-27 23:15
Actually it's my understanding that DTLS role changes are not support to happen between WebRTC endpoints.

But otherwise I agree that it seems sensible to only return channel ids after the SCTP association has been established and you have all the details influencing this decision.

**Comment by taylor-b** [comment] 2018-03-28 16:54
I think the spec covers all these cases (or at least intends to):

1. ID will be assigned once the DTLS role is determined.
2. ID will be assigned on creation. If it turns out that the number of streams negotiated later is too low, will be closed with an error.
3. `OperationError` thrown by `createDataChannel`.

As for DTLS role changes, we could say "only the *first* role selected matters"... Or we could just ignore this corner case, since the application always has the option of choosing IDs itself if needs to.

**Comment by lgrahl** [comment] 2018-03-29 11:16
You're correct, I found the section that covers the third case - it's in 6.2.:

> In some cases, the user agent may be unable to create an RTCDataChannel's underlying data transport. For example, the data channel's ID may be outside the range negotiated by the [RTCWEB-DATA] implementations in the SCTP handshake. When the user agent determines that an RTCDataChannel's underlying data transport cannot be created, the user agent MUST queue a task to run the following steps: [...]

But what's the point of assigning the ID while setting the remote description? The data channel doesn't open before the SCTP handshake took place. It would be much simpler to do ID assignment and validation once and not twice. And FWIW also much simpler to test since testing the second case before the third is very brittle.

> As for DTLS role changes, we could say "only the first role selected matters" [...]

Sounds good. Maybe make this an internal slot that can only be set once?

**Comment by jesup** [comment] 2018-03-30 06:16
When this was designed, Promises didn't exist...

**Comment by lgrahl** [comment] 2018-03-30 11:39
@jesup Fair point. But would you agree with the approach to simply not bother assigning IDs (leave it at `null`) until the SCTP assoc has been established?

**Comment by jesup** [comment] 2018-04-19 19:36
Changing id's to be assigned on SCTP connection will subtly change the behavior in observable ways; in particular anything sampling the id value on some other event that occurs when DTLS roles are known to be assigned might now get null.  Likely this is a small enough issue it won't break anyone (or close to no one).  I don't have a real problem with it, and I agree it makes testing that "hole" painful.

**Comment by lgrahl** [comment] 2018-04-21 23:58
@taylor-b If you don't oppose to this I can make a PR to only assign IDs once the SCTP association is up.

However, I will delay the PR until #1848 has been through the merge process since I can use the added *SCTP transport connected procedure* for this purpose.

**Comment by alvestrand** [comment] 2019-03-26 13:01
It seems that the spec had this halfway fixed, by specifying that id is nullable and not assigned until the DTLS role is assigned - but the fix missed the other half, that of specifying how to assign id once the DTLSTransport exists (which is what #2144 was about).
Closing #2144 as a duplicate of this one.

**Closed** 2019-10-03 14:30 UTC
Labels: Needs Test, PR exists
