### ISSUE TITLE
How to manage RTCRtpTransceivers for incoming MediaStreamTracks?

### ISSUE THREAD

**Issue by mparis** [w3c/webrtc-pc#623] opened 2016-05-05 13:58 UTC
Hello,
when a remote MediaStreamTrack is processed, what happens if there is not any transceiver to manage it?

1. Should a new transceiver be created automatically?
2. Should the API have an event to notify the user if he wants to create a new transceiver to manage the incoming media? So:
  - if the user creates a new one, the media will be accepted (local SDP with "a=recvonly" or "a=sendrecv")
  - if the user does not create a new one, the media will be rejected (local SDP with: "a=sendonly" or "a=inactive")

From my point of view, this question is quite interesting in the case that an endpoint does not know how many tracks the remote endpoint will offer it.

In the current document, [1] only says that a new receiver has to be created.

Refs
[1] http://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks

**Comment by taylor-b** [comment] 2016-05-05 20:18
This may be the same as issue #563.

**Comment by aboba** [comment] 2016-05-11 02:30
I have a slightly different question, which is what event occurs on the remote peer when transceiver.stop() is called on the local peer.  Presumably the negotiation-needed flag is set on the local peer, there is an O/A exchange and somehow the application on the remote peer finds out that the transceiver has been stopped.  Does this happen via an event?

**Comment by mparis** [comment] 2016-05-11 21:36
Hello @aboba,
I think that an _ended_ event should happen in the track of the related remote RtpReceiver as described in [1], [2] and [3].

Anyway, this is not related with the initial question of this issue, could we open another one for your question?

Best regards!!

Refs
[1] http://w3c.github.io/webrtc-pc/#processing-remote-mediastreamtracks
[2] http://w3c.github.io/webrtc-pc/#mediastreamtrack
[3] http://w3c.github.io/webrtc-pc/#widl-RTCPeerConnection-removeTrack-void-RTCRtpSender-sender

**Comment by alvestrand** [comment] 2016-05-19 14:27
Duplicate of #563. Closing.

**Closed by alvestrand** 2016-05-19 14:27 UTC
