### ISSUE TITLE
Trickled candidates may be added to the wrong session description

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-pc#811] opened 2016-09-22 10:54 UTC
Currently, addIceCandidate adds a candidate to the pending remote description if there is one, and the current remote description otherwise.  But if the remote peer has started an ICE restart and not yet received the answer from the local peer, the remote peer may trickle candidates for both session descriptions at the same time.  The choice of which session description to apply it to must be done using the ufrag, otherwise candidates for the old (current) description will be wrongly added to the new (pending) description.

This is similar to issues #760, #757,  and #726.

**Comment by taylor-b** [comment] 2016-11-03 20:36
This seems identical to issue #726. I'd suggest closing it to reduce confusion.

**Comment by alvestrand** [comment] 2016-11-08 12:07
Closing as duplicate of #726

**Closed by alvestrand** 2016-11-08 12:07 UTC
Labels: November interim topic
